version: '3'

services:
  xeyes:
    image: xeyes
    build:
      context: .
      dockerfile: Dockerfile.dev
      # volumes:
      # - ${HOME}/.Xauthority:/home/docker/.Xauthority:rw
      # - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}

    tty: true
    stdin_open: true
    # network_mode: 'host'
    # privileged: true
